"""Schema definitions for OpsCloud."""

from opscloud.schema.interrupts import (
    # Tool Approvals / HITL
    ActionRequest,
    ApproveDecision,
    AutoApproveAllDecision,
    EditDecision,
    HITLRequest,
    HitlDecision,
    HitlResumePayload,
    RejectDecision,
    ReviewConfig,
    SmartApproveAllDecision,
    SwitchManualDecision,
    # Ask User Protocol
    ASK_USER_ANSWERED_SUMMARY,
    ASK_USER_CANCELLED_ANSWER,
    ASK_USER_CANCELLED_SUMMARY,
    ASK_USER_ERROR_ANSWER_PREFIX,
    ASK_USER_FAILED_SUMMARY,
    ASK_USER_NOTHING_SELECTED,
    ASK_USER_NO_ANSWER,
    AskUserAnswered,
    AskUserCancelled,
    AskUserRequest,
    AskUserResumePayload,
    AskUserWidgetResult,
    CHOICE_QUESTION_TYPES,
    Choice,
    QUESTION_TYPES,
    Question,
    QuestionType,
    ValidatedQuestion,
    ask_user_answer_is_empty,
    decode_multi_select_answer,
    encode_multi_select_answer,
    format_ask_user_error_answer,
    format_ask_user_transcript,
    render_ask_user_transcript_for_display,
    # Goal & Criteria Review
    GoalReviewRequest,
    GoalReviewResumePayload,
    # Hook Invocation Interrupts
    HOOK_INVOCATION_INTERRUPT_TYPE,
    HookInvocationInterrupt,
    HookInvocationRequest,
    HookInvocationResponse,
    build_hook_interrupt_payload,
    build_hook_resume_value,
    is_hook_interrupt_payload,
    parse_hook_interrupt_payload,
    parse_hook_resume_value,
)

__all__ = [
    # HITL & Tool Approval
    "ActionRequest",
    "ApproveDecision",
    "AutoApproveAllDecision",
    "EditDecision",
    "HITLRequest",
    "HitlDecision",
    "HitlResumePayload",
    "RejectDecision",
    "ReviewConfig",
    "SmartApproveAllDecision",
    "SwitchManualDecision",
    # Ask User Protocol
    "ASK_USER_ANSWERED_SUMMARY",
    "ASK_USER_CANCELLED_ANSWER",
    "ASK_USER_CANCELLED_SUMMARY",
    "ASK_USER_ERROR_ANSWER_PREFIX",
    "ASK_USER_FAILED_SUMMARY",
    "ASK_USER_NOTHING_SELECTED",
    "ASK_USER_NO_ANSWER",
    "AskUserAnswered",
    "AskUserCancelled",
    "AskUserRequest",
    "AskUserResumePayload",
    "AskUserWidgetResult",
    "CHOICE_QUESTION_TYPES",
    "Choice",
    "QUESTION_TYPES",
    "Question",
    "QuestionType",
    "ValidatedQuestion",
    "ask_user_answer_is_empty",
    "decode_multi_select_answer",
    "encode_multi_select_answer",
    "format_ask_user_error_answer",
    "format_ask_user_transcript",
    "render_ask_user_transcript_for_display",
    # Goal & Criteria Review
    "GoalReviewRequest",
    "GoalReviewResumePayload",
    # Hook Invocation Interrupts
    "HOOK_INVOCATION_INTERRUPT_TYPE",
    "HookInvocationInterrupt",
    "HookInvocationRequest",
    "HookInvocationResponse",
    "build_hook_interrupt_payload",
    "build_hook_resume_value",
    "is_hook_interrupt_payload",
    "parse_hook_interrupt_payload",
    "parse_hook_resume_value",
]
