"""State models, cloud operational channels, and persistence for OpsCloud."""

from opscloud.state.base import (
    AgentState,
    BaseAgentState,
    OpsCloudAgentState,
)
from opscloud.state.cloud_context import (
    AWSContext,
    AzureContext,
    CloudContextState,
    CloudEnvironmentContext,
    CloudProvider,
    CloudResourceAction,
    CloudResourceRef,
    GCPContext,
    IaCContext,
    K8sContext,
    coerce_cloud_provider,
    format_cloud_badge,
    make_resource_ref,
)
from opscloud.state.goal_channels import (
    INHERIT_RUBRIC_MODEL,
    RUBRIC_RESULT_VALUES,
    GoalProposalKind,
    GoalRubricChannels,
    GoalStatus,
    coerce_goal_proposal_kind,
    coerce_goal_status,
    coerce_model_spec,
)
from opscloud.state.goal_state_limits import (
    GOAL_APPLICATION_CHAR_LIMIT,
    GOAL_NOTICE_TEXT_CHAR_LIMIT,
    GOAL_OBJECTIVE_CHAR_LIMIT,
    GOAL_STATUS_NOTE_CHAR_LIMIT,
    GOAL_STATUS_VALUES,
    RUBRIC_CHAR_LIMIT,
    GoalStateSizeError,
    validate_goal_application,
    validate_goal_application_total,
    validate_goal_objective,
    validate_goal_status_note,
    validate_rubric,
)
from opscloud.state.resume_state import ResumeState
from opscloud.state.service_context import (
    ManagedService,
    ServiceContextState,
    ServiceOperationRecord,
    ServiceOperationType,
    ServiceStatus,
    make_operation_record,
    make_service_record,
)
from opscloud.state.session import (
    SessionManager,
    ThreadInfo,
    delete_thread,
    find_similar_threads,
    format_relative_timestamp,
    format_timestamp,
    generate_thread_id,
    get_checkpointer,
    get_db_path,
    get_most_recent,
    list_threads,
    prewarm_thread_message_counts,
    set_db_path,
    thread_exists,
)
from opscloud.state.state_migration import migrate_legacy_state

__all__ = [
    # Core Composite State
    "AgentState",
    "BaseAgentState",
    "OpsCloudAgentState",
    # Cloud Operations Context
    "AWSContext",
    "AzureContext",
    "CloudContextState",
    "CloudEnvironmentContext",
    "CloudProvider",
    "CloudResourceAction",
    "CloudResourceRef",
    "GCPContext",
    "IaCContext",
    "K8sContext",
    "coerce_cloud_provider",
    "format_cloud_badge",
    "make_resource_ref",
    # Service Management & Plugin State
    "ManagedService",
    "ServiceContextState",
    "ServiceOperationRecord",
    "ServiceOperationType",
    "ServiceStatus",
    "make_operation_record",
    "make_service_record",
    # Goal & Rubric Channels
    "GOAL_APPLICATION_CHAR_LIMIT",
    "GOAL_NOTICE_TEXT_CHAR_LIMIT",
    "GOAL_OBJECTIVE_CHAR_LIMIT",
    "GOAL_STATUS_NOTE_CHAR_LIMIT",
    "GOAL_STATUS_VALUES",
    "GoalProposalKind",
    "GoalRubricChannels",
    "GoalStateSizeError",
    "GoalStatus",
    "INHERIT_RUBRIC_MODEL",
    "RUBRIC_CHAR_LIMIT",
    "RUBRIC_RESULT_VALUES",
    "coerce_goal_proposal_kind",
    "coerce_goal_status",
    "coerce_model_spec",
    "validate_goal_application",
    "validate_goal_application_total",
    "validate_goal_objective",
    "validate_goal_status_note",
    "validate_rubric",
    # Resume State
    "ResumeState",
    # Session Persistence & Checkpointing
    "SessionManager",
    "ThreadInfo",
    "delete_thread",
    "find_similar_threads",
    "format_relative_timestamp",
    "format_timestamp",
    "generate_thread_id",
    "get_checkpointer",
    "get_db_path",
    "get_most_recent",
    "list_threads",
    "prewarm_thread_message_counts",
    "set_db_path",
    "thread_exists",
    # Migration
    "migrate_legacy_state",
]
