"""Configuration management and options registry for OpsCloud."""

from opscloud.config.aws import (
    AWSConfig,
    AWSIdentity,
    get_aws_config,
    get_aws_context,
    get_aws_credentials_dict,
    get_boto3_session,
    resolve_aws_identity,
)
from opscloud.config.manifest import (
    ConfigOption,
    OptionKind,
    get_config_options,
    get_option,
    get_option_by_db_key,
    iter_groups,
    load_config_toml,
    option_keys,
    resolve_scalar,
)
from opscloud.config.metadata import build_coding_agent_metadata, build_stream_config
from opscloud.config.paths import (
    CONFIG_FILE_PATH,
    CONFIG_PATH,
    DATA_DIR,
    DEFAULT_AGENT_NAME,
    ENV_PREFIX,
    GLOBAL_ENV_PATH,
    OPSCLOUD_HOME,
    PLUGINS_CACHE_DIR,
    SERVER_RUNTIME_DIR,
    SESSIONS_DB_PATH,
    STATE_DIR,
    USER_HOME,
    find_project_root,
)
from opscloud.config.settings import (
    Settings,
    get_glyphs,
    get_settings,
    reload_from_store,
    reload_settings,
    resolve_env_var,
    settings,
    sync_aws_env_aliases,
)
from opscloud.config.store import ConfigCategory, ConfigEntry, ConfigStore, ConfigValue
from opscloud.config.store_factory import create_config_store, create_config_store_sync

__all__ = [
    "AWSConfig",
    "AWSIdentity",
    "CONFIG_FILE_PATH",
    "CONFIG_PATH",
    "ConfigCategory",
    "ConfigEntry",
    "ConfigOption",
    "ConfigStore",
    "ConfigValue",
    "DATA_DIR",
    "DEFAULT_AGENT_NAME",
    "ENV_PREFIX",
    "GLOBAL_ENV_PATH",
    "OPSCLOUD_HOME",
    "OptionKind",
    "PLUGINS_CACHE_DIR",
    "SERVER_RUNTIME_DIR",
    "SESSIONS_DB_PATH",
    "STATE_DIR",
    "Settings",
    "USER_HOME",
    "build_coding_agent_metadata",
    "build_stream_config",
    "create_config_store",
    "create_config_store_sync",
    "find_project_root",
    "get_aws_config",
    "get_aws_context",
    "get_aws_credentials_dict",
    "get_boto3_session",
    "get_config_options",
    "get_glyphs",
    "get_option",
    "get_option_by_db_key",
    "get_settings",
    "iter_groups",
    "load_config_toml",
    "option_keys",
    "reload_from_store",
    "reload_settings",
    "resolve_aws_identity",
    "resolve_env_var",
    "resolve_scalar",
    "settings",
    "sync_aws_env_aliases",
]
