"""Canonical registry of `OPSCLOUD_*` environment variables.

Every env var the app reads whose name starts with `OPSCLOUD_` should
be defined here as a module-level constant.
"""

from __future__ import annotations

import os

AUTO_UPDATE = "OPSCLOUD_AUTO_UPDATE"
COLLAPSE_PASTES = "OPSCLOUD_COLLAPSE_PASTES"
DEBUG = "OPSCLOUD_DEBUG"
DEBUG_FILE = "OPSCLOUD_DEBUG_FILE"
DEFAULT_DEBUG_FILE = "/tmp/opscloud_debug.log"
LOG_LEVEL = "OPSCLOUD_LOG_LEVEL"
LOG_DIR = "OPSCLOUD_LOG_DIR"
LOG_DIRECTORY = "OPSCLOUD_LOG_DIRECTORY"
LOG_FILE = "OPSCLOUD_LOG_FILE"
LOG_CONSOLE = "OPSCLOUD_LOG_CONSOLE"
LOG_TO_FILE = "OPSCLOUD_LOG_TO_FILE"
DEFAULT_LOG_DIR = "/tmp/opscloud_logs"
DEFAULT_LOG_FILE = "opscloud.log"
DEBUG_MCP_PROJECT_TRUST = "OPSCLOUD_DEBUG_MCP_PROJECT_TRUST"
DEBUG_NOTIFICATIONS = "OPSCLOUD_DEBUG_NOTIFICATIONS"
DEBUG_ONBOARDING = "OPSCLOUD_DEBUG_ONBOARDING"
DEBUG_UPDATE = "OPSCLOUD_DEBUG_UPDATE"
DISABLED_PROJECT_MCP_SERVERS = "OPSCLOUD_DISABLED_PROJECT_MCP_SERVERS"
ENABLED_PROJECT_MCP_SERVERS = "OPSCLOUD_ENABLED_PROJECT_MCP_SERVERS"
EXTERNAL_EVENT_SOCKET = "OPSCLOUD_EXTERNAL_EVENT_SOCKET"
EXTERNAL_EVENT_SOCKET_PATH = "OPSCLOUD_EXTERNAL_EVENT_SOCKET_PATH"
EXTRA_SKILLS_DIRS = "OPSCLOUD_EXTRA_SKILLS_DIRS"
EXPERIMENTAL = "OPSCLOUD_EXPERIMENTAL"
HIDE_CWD = "OPSCLOUD_HIDE_CWD"
HIDE_GIT_BRANCH = "OPSCLOUD_HIDE_GIT_BRANCH"
HIDE_LANGSMITH_TRACING = "OPSCLOUD_HIDE_LANGSMITH_TRACING"
HIDE_SPLASH_VERSION = "OPSCLOUD_HIDE_SPLASH_VERSION"
KITTY_KEYBOARD = "OPSCLOUD_KITTY_KEYBOARD"
LANGSMITH_PROJECT = "OPSCLOUD_LANGSMITH_PROJECT"
LANGSMITH_REDACT = "OPSCLOUD_LANGSMITH_REDACT"
LANGSMITH_REPLICA_PROJECTS = "OPSCLOUD_LANGSMITH_REPLICA_PROJECTS"
NO_TERMINAL_ESCAPE = "OPSCLOUD_NO_TERMINAL_ESCAPE"
NO_UPDATE_CHECK = "OPSCLOUD_NO_UPDATE_CHECK"
OFFLINE = "OPSCLOUD_OFFLINE"
OLLAMA_DISCOVERY = "OPSCLOUD_OLLAMA_DISCOVERY"
ONBOARDING_INTEGRATIONS_SCREEN = "OPSCLOUD_ONBOARDING_INTEGRATIONS_SCREEN"
RESTARTED_AFTER_UPDATE = "OPSCLOUD_RESTARTED_AFTER_UPDATE"
RIPGREP_INSTALLER = "OPSCLOUD_RIPGREP_INSTALLER"
SERVER_ENV_PREFIX = "OPSCLOUD_SERVER_"
SHELL_ALLOW_LIST = "OPSCLOUD_SHELL_ALLOW_LIST"
SHOW_HEADER = "OPSCLOUD_SHOW_HEADER"
SHOW_LANGSMITH_REPLICA_TRACING = "OPSCLOUD_SHOW_LANGSMITH_REPLICA_TRACING"
SHOW_SCROLLBAR = "OPSCLOUD_SHOW_SCROLLBAR"
SHOW_URL_OPEN_TOAST = "OPSCLOUD_SHOW_URL_OPEN_TOAST"
SPLASH_SHOW_CWD = "OPSCLOUD_SPLASH_SHOW_CWD"
SPLASH_SHOW_MODEL = "OPSCLOUD_SPLASH_SHOW_MODEL"
SUPPRESS_ENV_OVERRIDE_WARNING = "OPSCLOUD_SUPPRESS_ENV_OVERRIDE_WARNING"
THEME = "OPSCLOUD_THEME"
USER_ID = "OPSCLOUD_USER_ID"

_TRUTHY_VALUES = frozenset({"1", "true", "yes", "on"})
_FALSY_VALUES = frozenset({"0", "false", "no", "off", ""})


def classify_env_bool(raw: str) -> bool | None:
    """Classify a raw env-var string as a truthy, falsy, or unrecognized token."""
    lowered = raw.strip().lower()
    if lowered in _TRUTHY_VALUES:
        return True
    if lowered in _FALSY_VALUES:
        return False
    return None


def is_env_truthy(name: str, *, default: bool = False) -> bool:
    """Return whether env var name is set to a recognizably truthy value."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    classified = classify_env_bool(raw)
    return default if classified is None else classified
